### ISSUE TITLE
Add a "vegetable" field to REST API

### ISSUE THREAD

**Issue by noraeiffman** [treflehq/trefle-api#10]
Right now I feel overwhelmed when I try to browse plants, because there is way too many.

It would be interesting to split "all the plants" and just the vegetables, maybe by making a specific set of API calls for farming plants.

**Comment by LorienOlive** [comment]
@noraeiffman I really like this idea.  House plants would be a helpful distinction for the project I'm working on.

**Comment by lambda2** [comment]
This is plan indeed 😄.

Adding "house plants" is an interesting lead, but I'm afraid that too many plants could be considered as house plants. On which criteria can we establish that a plant is an "house plant" ?
