### ISSUE TITLE
Missing Plant Info - Hoya Carnosa Compacta

### ISSUE THREAD

**Issue by lundjrl** [treflehq/trefle-api#114]
**Describe the bug**
Searching for a Hoya Carnosa Compacta doesn't yield the correct result.

**To Reproduce**
1. Try this curl: curl --request GET \
  --url 'https://trefle.io/api/v1/plants/search?token=<TOKEN>&q=hoya%20carnosa%20compacta'

**Expected behavior**
Results for a Hoya Carnosa Compacta or "Hindu Rope Plant"

**Screenshots**
Check the results of the curl request.

**Comment by lambda2** [comment]
Hey @lundjrl , seems that's Hoya Carnosa Compacta [is a synonym](https://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:940449-1) of [hoya carnosa]( https://trefle.io/explore/species/hoya-carnosa#synonyms)

**Comment by lundjrl** [comment]
@lambda2 
Ah, I see. So each variation of a Carnosa is under the same entry. I thought ones like the Krimson Queen and Compacta would be separate entries.
