### ISSUE TITLE
Planting density inconsistency

### ISSUE THREAD

**Issue by kessl** [treflehq/trefle-api#20]
I stumbled upon an inconsistency in the planting density fields - I couldn't figure out how the values in acres and square meters relate.

Take for example the American Hornbeam (https://trefle.io/api/plants/117252):
`planting_density_minimum: sqm: 2832802, acre: 700`

700 trees per acre amount to **5.78** square meters per tree.
2 832 802 per square meter is obviously too many. If I assume 'sqm' refers to a square kilometer, I get **35.3** square meters per tree.

What am I missing?

**Comment by lambda2** [comment]
Hey @kessl , seems to be an issue indeed. We'll dig into it
