### ISSUE TITLE
How does search work?

### ISSUE THREAD

**Issue by alext234** [treflehq/trefle-api#25]
For example, with this query

```
https://trefle.io/api/plants?q=rose
```
How does the API search based on the given keyword? Some of the common names returned does not have any `rose` inside.

**Comment by lambda2** [comment]
Hey @alext234 , sorry for the late reply.
When we try it, they all have `rose` somehow in their common name or scientific name.
Like:
<img width="643" alt="Screenshot 2020-06-11 at 05 18 33" src="https://user-images.githubusercontent.com/3030511/84341300-0fb8a700-aba3-11ea-8d02-238a7ef56d60.png">
