### ISSUE TITLE
Ability to add data

### ISSUE THREAD

**Issue by GreenThumbAU** [treflehq/trefle-api#26]
I'm using the API to prefill data for plants in our app's admin, when we add/create them. There are a few that Trefle returns as empty [] or complete_data = false and I'm wondering if you're considering adding the ability to add or update data via the API. That way, when we complete adding a plant to our database, we could also add it to Trefle or update incomplete data. Thoughts?

**Comment by lambda2** [comment]
That's planned for the next release !
