### ISSUE TITLE
Contact email (hello@trefle.io) doesn't work

### ISSUE THREAD

**Issue by jetamartin** [treflehq/trefle-api#30]
I've tried sending multiple emails (on 5/2/2020, 5/3/2020) to hello@trefle.io (email listed on website for contact info) and each and every time I get a failure to deliver notice. Is this email address no longer operational? Is there alternative email address where I could send questions?  

Cheers

**Comment by jetamartin** [comment]
Can anybody tell me whether this API is even "active"...was considering using it for my Web capstone project (Planning your Xeriscape Garden) but I don't want to use an API where you can't get support or is incomplete. From my simple query it looked like none of the plants that I retrieved via the api had any "detailed" data associated with them. 
Thanks

**Comment by lambda2** [comment]
Hey @jetamartin, thanks for reporting the malfunction of the email aliases, they're working now.

About the activity of this project, you shouldn't use it right now to build a "production grade" app. The data is still incomplete, and we're missing funding and manpower to maintain it.
We'll open-source it soon, hoping this will help 🙏

Regards

**Comment by jetamartin** [comment]
Thanks for fixing it.
