### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by rsu819** [treflehq/trefle-api#43]
**Describe the bug**
Getting a 504 Gateway Time-out response
**To Reproduce**
1. Submit API GET request on Postman to 'https://trefle.io/api/v1/plants/search?q=rose&token={{token}}'
2. Hit Send
3. See error, no valid JSON response

**Expected behavior**
A JSON object should return with zero or more entries of plants in the database. 

**Screenshots**
Also, I notice the site is also down currently. 

![Screen Shot 2020-08-06 at 5 57 44 PM](https://user-images.githubusercontent.com/53282793/89597394-e4eb7780-d80e-11ea-9385-1cd710572680.png)

![Screen Shot 2020-08-06 at 5 59 10 PM](https://user-images.githubusercontent.com/53282793/89597406-ed43b280-d80e-11ea-970b-24d720dd7bc8.png)

**Additional context**
This is an intermittent problem. Sometimes the responses come back just fine, but every other time seems to be an issue.

**Comment by HiceS** [comment]
I can confirm I'm also experiencing this.

**Comment by lambda2** [comment]
Hey @HiceS & @rsu819 . We're experiencing high load since yesterday, and we're doing our best to go back to a proper performance 🙏

**Comment by rsu819** [comment]
I've been using this API for a class project, and has been an awesome resource otherwise. Thanks for your hard work!

**Comment by HiceS** [comment]
of for sure dude I took a look at your endpoint board, looks like you got your hands full at the moment.
