### ISSUE TITLE
Grammar mistake on trefle.io landing page

### ISSUE THREAD

**Issue by capndave** [treflehq/trefle-api#47]
**Describe the bug**
On the landing page, under A Complete Plants API for ... students, "Get in touch ! We try to support as much as we can educational projects !" should be changed to "Get in touch! We try to support educational projects as much as we can!"

**Comment by capndave** [comment]
I'm happy to make this change if you like - let me know!

**Comment by lambda2** [comment]
Hey @capndave, thanks for the report !
