### ISSUE TITLE
swagger.yaml isn't valid OpenAPI 3.0

### ISSUE THREAD

**Issue by MikeRalphson** [treflehq/trefle-api#51]
**Describe the bug**
The published `swagger.yaml` isn't valid according to the OpenAPI 3.0 specification.

**To Reproduce**
1. Go to `https://petstore.swagger.io`
2. Import `https://docs.trefle.io/swagger.yaml`
3. Scroll down to `Invalid` at the bottom of the page
4. Click to see errors (`type` properties on `parameters` etc)

**Expected behavior**
The `swagger.yaml` should pass OpenAPI 3.0 validation for improved interoperability.

**Comment by lambda2** [comment]
Thanks ! We'll take a look !
