### ISSUE TITLE
Allow filtering by several values

### ISSUE THREAD

**Issue by lambda2** [treflehq/trefle-api#6]
For example, `GET api/plants?max_height=4.0` would return any plants up to 4.0 feet.

And `GET api/plants?flower_color=Red,Pink` would return any plants with Red or Pink flowers.

**Comment by tabuckner** [comment]
+1 on this one!

I dropped a question into Slack about something similar. 

My specific use case was to get all plants with a minimum temperature that is `>=` the query param value. However, filtering by range would solve that problem _and_ be more generic.

That said--if my request is easier, I selfishly want that! 😜 

I'm happy to make a PR--I just can't find the repo.
