### ISSUE TITLE
Fix dead image links

### ISSUE THREAD

**Issue by lambda2** [treflehq/trefle-api#67]
Some image links are broken, find a way to automate a weekly check of the image links, and drop them if invalid

**Comment by Baza207** [comment]
Maybe adding to this, some items also return `http://` urls but just changing them to `https://` the link still works. If you're looking into a way to automate culling deal image links, it might be a good place to try this too?

An example being "Hairy cat's ear" id `144423`. The image url is `http://d2seqvvyy3b8p2.cloudfront.net/6d0af0bfb352c0254ea3019d7b6a5844.jpg` but changing it to `https://d2seqvvyy3b8p2.cloudfront.net/6d0af0bfb352c0254ea3019d7b6a5844.jpg` works fine.

There's a few other's like this as well, but this one is the name I remember 😂.

**Comment by lambda2** [comment]
Good point ! I'll add a check to change to `https` all the `http://` links that are still valid in https 👍
