### ISSUE TITLE
confirmation email

### ISSUE THREAD

**Issue by jonmarron** [treflehq/trefle-api#70]
Don't know if it is a bug or what exactly, but I am not getting y confirmation email to Sign in
:)

**Comment by lambda2** [comment]
Hey @jonmarron. If it's an hotmail address, we have an issue with theses ones, but you should be validated now. Else, send us a mail at hello@trefle.io, we'll confirm you manually 🔧

**Comment by jonmarron** [comment]
hi @lambda2 ! Thank you, I'm confirmed now! thanks for the support!
Cheers,
Jon
