### ISSUE TITLE
species request causing data array to be empty

### ISSUE THREAD

**Issue by splintercell9dev** [treflehq/trefle-api#82]
**Describe the bug**
When requesting API for 'ficus-microcarpa' through URL 'https://trefle.io/api/v1/species/search?token=ACCESS_TOKEN&q=Ficus microcarpa' data array is returning empty data array. Does the data for this species not exists?

**To Reproduce**
Steps to reproduce the behavior(using nodejs):
`const fetch = require('node-fetch') ;
require('dotenv').config() ;
const access_token = process.env.ACCESS_TOKEN ;
async function request(){
    const dataObj = await fetch(`https://trefle.io/api/v1/species/search?token=${access_token}&q=ficus microcarpa`)

    const json = await dataObj.json() ;
    return json
}

request().then( (json) => {
    console.log(json)
})`

**Expected behavior**
The result must be there as its records are present over other websites.

**Comment by lambda2** [comment]
Hello @splintercell9dev. This species were missing, so it has been added properly.

**Comment by splintercell9dev** [comment]
@lambda2 Now this species is fixed. Now another species that was working perfectly before i.e `bauhinia-blakeana` is now giving error on request
`{
    "error": true,
    "message": "can't find record: \"bauhinia-blakeana\""
}`

**Comment by lambda2** [comment]
Hey, indeed some changes has been made to this species, that [is in fact an artificial hybrid](http://www.plantsoftheworldonline.org/taxon/urn:lsid:ipni.org:names:481142-1). The slug is now `bauhinia-x-blakeana`
