### ISSUE TITLE
expired SSL certificate?

### ISSUE THREAD

**Issue by funtimes1** [treflehq/trefle-api#86]
**Describe the bug**

Hello, it seems like trefle.io and trefle API are currently down due to an expired ssl certificate. 

**To Reproduce**
1. Go to 'trefle.io'
<img width="773" alt="Screenshot 2021-01-24 at 15 52 44" src="https://user-images.githubusercontent.com/65676039/105643661-7029f980-5e91-11eb-971d-d10b94066dc9.png">

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by lambda2** [comment]
Thanks for the report, it has been fixed !
